### PR TITLE
include a header in _toc.yml

### PR DESCRIPTION
**Pull request by najuzilu**
PR used to test sphinx version

### CODE REVIEW

**Comment by mmcky** [comment]
@najuzilu ok so that actually installed `0.0.7` so we probably need to regenerate the latest to get the latest look from `sphinx_book_theme`.

**Comment by najuzilu** [comment]
Just a quick note: my build is failing locally.

**Comment by mmcky** [comment]
@najuzilu I have just submitted a PR that will trigger a build of this repository every day to keep up with these underlying software changes. Can you keep an eye on the `Actions` tab for the next couple of days in case it pushes failed builds etc?

**Comment by najuzilu** [comment]
@mmcky :+1:

**Pull request closed without merging**
